### ISSUE TITLE
JRE Releases

### ISSUE THREAD

**Issue by sgerdes1998** [adoptium/temurin8-binaries#2]
We've been actively using and validating code against the JRE release for adoptopenjdk.  For v302, only the JDK versions exist.  Are there plans to release the JRE versions as well?

**Comment by karianna** [comment]
Yes, you'll see these coming out in the next few weeks.

**Comment by mibyge** [comment]
@karianna Do you have a more precise date?

We have thousands of devices in an enterprise that needs to have their AdoptOpenJDK JRE installation patched to be protected from the latest vulnerabilities, and our Vulnerability Management is not that happy about we now 3 weeks after release hasn't started patching at all.

Could you please consider building this release on AdoptOpenJDK so we are covered until you have sorted out whatever it is that keeps you from building them on Adoptium?

Thanks in advance :)
