### ISSUE TITLE
Binaries for missing Server JDK's and Windows x86 JDK/JRE

### ISSUE THREAD

**Issue by minduch** [adoptium/temurin8-binaries#3]
Two questions in one "issue", but they are relating to Binaries of the JDK/JRE:

1. Will there be any Windows x86 binaries? If so, will JDK 8 also have x86 binaries?
2. Will there be any "[headless] server JDK" binaries?

Thank you.

**Comment by karianna** [comment]
Yes on 1. (coming in the next two weeks), no on 2 (we recommend using jlink to build the runtime that you need).

**Comment by minduch** [comment]
Thank you for the quick reply, and the answer to the "headless" server JDK (I forgot about jlink).
