### ISSUE TITLE
Solaris SPARC builds?

### ISSUE THREAD

**Issue by hege-li** [adoptium/temurin8-binaries#4]
Any estimate when Solaris binaries will be available? Thanks.

**Comment by smlambert** [comment]
see this table for high-level status: https://github.com/adoptium/adoptium/issues/68 - sparcv9_solaris is in progress, but from the view inside the Temurin-compliance project where the compliance testing is being done, it will follow on the heels of x86_solaris (which is expected in the next day or so).
