### ISSUE TITLE
Latest release isn't the latest

### ISSUE THREAD

**Issue by OscarFarg** [adoptium/temurin8-binaries#7]
We use the GitHub API to get the latest JDK binaries and use https://github.com/adoptium/temurin8-binaries/releases/latest for that. However it now shows JDK8u302-b08.1 als latest release which is a Windows-only build while the 'real' latest release should be https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u312-b07 .

This makes it really complicated to automatically download new Temurin builds. Is there something that can be changed about that?

**Comment by karianna** [comment]
Please use the official API at https://api.adoptium.net

**Comment by OscarFarg** [comment]
I'm sorry I didn't know that existed. Many thanks for the fast reply!
